### ISSUE TITLE
Improvement over the translator.js

### ISSUE THREAD

**Issue by vcollado** [aabreuglez/wordReferenceBot#5]
It would be fine to do some modifications in the issued file,

So,
Group the parser functions over the "namespace" required, helping to keep the code more readable.
Use the functions .hasClass of jQuery ( api https://api.jquery.com/hasclass/ ) in replacement of **$(this).attr('class')**

**Comment by adrianabreu** [comment]
Hi, thank you.
You're totally right, I'll encapsulate the parser functions.
For hasClass I will use the cheerio implementation :)
