### ISSUE TITLE
Descripción 

### ISSUE THREAD

**Issue by ericsuarez** [aabreuglez/wordReferenceBot#7]
En mi opinión, para mejorar la usabilidad del mismo. Podrías incluir el apartado /help como descripción y que apareciera cuando se inicia el código con /start. Simplemente porque es un estándar en el desarrollo de bots y porque al no aparecer nada puede parecer que el bot esté inactivo.

**Comment by adrianabreu** [comment]
Hello! Thank you for the feedback, much obliged.

It's a simple task and I'll do it anyways but I would like to now where I can find that standard (pure academical reasons).
I have been looking for it and I just got this:
https://en.wikipedia.org/wiki/Wikipedia:Creating_a_bot#Specification

Thank you

**UPDATE:** Issue fixed, but waiting for your feedback @alu0100786330

**Comment by ericsuarez** [comment]
No es estándar en un libro, pero si que la mayoría de los bots importantes lo tienen. A eso me refería, un saludo.

**Comment by adrianabreu** [comment]
Oh, thank you anyway :+1:
